version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - server/.env
    ports:
      - 5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
