version: "3.1"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-testdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    ports:
      - "5434:3306"
    restart: always
